In [ ]:
#!conda update conda
#!pip install update pip
#!pip install update cobra
#!pip install update pip
#!pip install update  joblib 
#!pip install update  multiprocess
#!pip install update networkx
#!pip install update  pandas 
#!pip install update numpy 
#!pip install update scipy    
#normal.reactions.get_by_id("PHETHPTOX2").bounds = (0, 0.0)
#normal.reactions.get_by_id("r0399").bounds = (0.0, 0.0)
#cobra.io.save_json_model(normal, "PKU.json")
#model = cobra.io.load_matlab_model('GEM_Recon3_thermocurated_redHUMAN.mat')
#cobra.io.save_json_model(model, "GEM_Recon3_thermocurated_redHUMAN.json")

In [4]:
import cobra
import numpy as np
import warnings 
warnings.filterwarnings("ignore")

#GEM_Recon2_thermocurated_redHUMAN = cobra.io.load_matlab_model('GEM_Recon2_thermocurated_redHUMAN.mat')
#cobra.io.save_json_model(GEM_Recon2_thermocurated_redHUMAN, "GEM_Recon2_thermocurated_redHUMAN.json")
normal = cobra.io.load_json_model("GEM_Recon2_thermocurated_redHUMAN.json")
normal

In [5]:
print(
normal.reactions.get_by_id("PHETHPTOX2").bounds,
normal.reactions.get_by_id("r0399").bounds)

(0.0, 100.0) (-100.0, 100.0)

In [8]:
import pandas as pd

#por ejemplo una funcion: input: lista de metabolitos; output: todos los campos.
frozen       = normal.metabolites.get_by_id("tyr_L_e").reactions.union(normal.metabolites.get_by_id("tyr_L_c").reactions).union(normal.metabolites.get_by_id("tyr_L_m").reactions)
tyr_L_ids    = [list(frozen)[i].id for i in range(0,len(frozen))]
tyr_L_names  = [list(frozen)[i].name for i in range(0,len(frozen))]
tyr_L_rxns   = [list(frozen)[i].reaction for i in range(0,len(frozen))]
list_of_tuples   = list(zip(tyr_L_ids, tyr_L_names, tyr_L_rxns))  
columns          = ["tyr_L_e_ids","tyr_L_e_names","tyr_L_e_rxns"]
tyr_L          =  pd.DataFrame(list_of_tuples, columns = columns)  

frozen         = normal.metabolites.get_by_id("phe_L_e").reactions.union(normal.metabolites.get_by_id("phe_L_c").reactions).union(normal.metabolites.get_by_id("phe_L_m").reactions)
phe_L_ids    = [list(frozen)[i].id for i in range(0,len(frozen))]
phe_L_names  = [list(frozen)[i].name for i in range(0,len(frozen))]
phe_L_rxns   = [list(frozen)[i].reaction for i in range(0,len(frozen))]

list_of_tuples   = list(zip(phe_L_ids,phe_L_names, phe_L_rxns))  
columns          = ["phe_L_e_ids","phe_L_e_names","phe_L_e_rxns"]
phe_L          =  pd.DataFrame(list_of_tuples, columns = columns)

## FBA

In [78]:

solution_normal = normal.optimize()
phe_L_fluxes   = solution_normal.fluxes[phe_L_ids].to_frame() #
phe_L_fluxes.query('abs(fluxes) > 1e-10', inplace=True)
phe_L_fluxes.rename_axis('phe_L_e_ids').reset_index()
phe_L_fluxes = phe_L_fluxes.rename_axis('phe_L_e_ids').reset_index()
pd.merge(phe_L_fluxes, phe_L)

,phe_L_e_ids,fluxes,phe_L_e_names,phe_L_e_rxns
0,r1764,0.829787,Y+LAT2 Utilized transport,gln_L_c + na1_e + phe_L_e --> gln_L_e + na1_c ...
1,EX_phe_L_e,-0.829787,exchange reaction for L-phenylalanine,phe_L_e <--
2,biomass,3.198056,Generic human biomass reaction,0.505626 ala_L_c + 0.35926 arg_L_c + 0.279425 ...

In [77]:
tyr_L_fluxes   = sol_normal.fluxes[tyr_L_ids].to_frame()  #.query('abs(fluxes) > 1e-7', inplace=True)
tyr_L_fluxes.query('abs(fluxes) > 1e-10', inplace=True)
tyr_L_fluxes = tyr_L_fluxes.rename_axis('tyr_L_e_ids').reset_index()
pd.merge(tyr_L_fluxes, tyr_L)

,tyr_L_e_ids,fluxes,tyr_L_e_names,tyr_L_e_rxns
0,EX_tyr_L_e,-0.510637,L-Tyrosine exchange,tyr_L_e <=>
1,r1634,-1.744680,Amino Acid-Polyamine-Organocation (APC) TCDB:2...,ile_L_c + tyr_L_e <=> ile_L_e + tyr_L_c
2,TYRt,2.255317,L-tyrosine transport,tyr_L_e <=> tyr_L_c
3,biomass,3.198056,Generic human biomass reaction,0.505626 ala_L_c + 0.35926 arg_L_c + 0.279425 ...

# Phenotypic space

## Finding glucose and oxygen uptakes

In [110]:
normal.metabolites[1]

In [127]:
#normal.
#[list(frozen)[i].reaction for i in range(0,len(frozen))]

rxn_names      = [normal.reactions[i].name for i in range(0, len(normal.reactions))]
rxn_ids        = [normal.reactions[i].id for i in range(0, len(normal.reactions))]
rxn_reaction   = [normal.reactions[i].reaction for i in range(0, len(normal.reactions))]

model_df_rxns       = pd.DataFrame(list(zip(rxn_ids,rxn_names, rxn_reaction)), columns = ['rxn_ids','rxn_names',"rxn_reaction"])


met_names      = [normal.metabolites[i].name for i in range(0, len(normal.metabolites))]
met_ids        = [normal.metabolites[i].id for i in range(0, len(normal.metabolites))]
met_formula   = [normal.metabolites[i].formula for i in range(0, len(normal.metabolites))]

model_df_mets       = pd.DataFrame(list(zip(met_ids,met_names, met_formula)), columns = ['met_ids','met_names',"met_formula"])

model_df_mets[model_df_mets.met_ids.str.contains('glc_D_')]
#model_df_mets[model_df_mets.met_ids.str.contains('^o2_')]

      met_ids  met_names met_formula
628   glc_D_e  D-glucose     C6H12O6
810   glc_D_c  D-glucose     C6H12O6
907   glc_D_r  D-glucose     C6H12O6
1944  glc_D_l  D-glucose     C6H12O6
2032  glc_D_g  D-glucose     C6H12O6

In [126]:
def metabolites2reactions(modelo, metabolitos): # Toma metabolitos
  """Crea un agregado de las reacciones segun un listado de metabolitos. 

  Parameters
  ----------
  modelo: model
      El modelo inicial del cual se toman las reacciones
  metabolitos : list
      IDs de un metabolito. La función acepta multiples para crear un joint. 

  Returns
  -------
  df
      crea un dataframe pandas agregada de ids, nombre de reacciones, y reacciones en si
  """
  frozen = modelo.metabolites.get_by_id(metabolitos[0]).reactions # Crea el inicio
  for met in metabolitos: # Añade metabolistos al listado de reacciones
    frozen = frozen.union(modelo.metabolites.get_by_id(met).reactions)
  
  ids   = [list(frozen)[i].id       for i in range(0,len(frozen))] # List Comprehesion
  names = [list(frozen)[i].name     for i in range(0,len(frozen))]
  rxns  = [list(frozen)[i].reaction for i in range(0,len(frozen))]

  list_of_tuples = list(zip(ids, names, rxns))     # DataFrame en Python; crea triplets
  columns        = ["ids","names","rxns"]   # Titulos de columnas de la tripleta
  df             =  pd.DataFrame(list_of_tuples, columns = columns) # Titulos asignados a la lista de tuplas
  
  return df

In [136]:
glucose_oxygen = metabolites2reactions(normal, ["o2_e", "glc_D_e"])
glucose_oxygen[glucose_oxygen.names.str.contains('exchange')]

         ids                         names          rxns
3    EX_o2_e  exchange reaction for oxugen     o2_e <--
26  EX_glc_e            D-Glucose exchange  glc_D_e <=>

## Varying glucose and oxygen uptakes

### Uptakes bounds in the model and in the optimal solution

In [153]:
normal.reactions.get_by_id("EX_o2_e").bounds
normal.reactions.get_by_id("EX_glc_e").bounds

(-1.0, 100.0)

In [154]:
upkates = ["EX_o2_e","EX_glc_e"]
solution_normal[upkates]

EX_o2_e    -6.933845
EX_glc_e    0.000000
Name: fluxes, dtype: float64

In [192]:
pd.set_option('display.max_rows', None)

solution_normal_df          = pd.merge(solution_normal.to_frame().rename_axis('rxn_ids').reset_index(),model_df_rxns)
solution_normal_df_filtered = solution_normal_df.query('abs(fluxes) > 1e-10') 
solution_normal_df_filtered[solution_normal_df_filtered.rxn_ids.str.contains('EX')]

,rxn_ids,fluxes,reduced_costs,rxn_names,rxn_reaction
1214,EX_4abut_e,-0.531917,0.000000e+00,4-Aminobutanoate exchange,4abut_e <=>
1240,EX_acald_e,8.407364,0.000000e+00,Acetaldehyde exchange,acald_e <=>
1245,EX_ach_e,-1.000000,4.146097e-16,Acetylcholine exchange,ach_e <=>
1251,EX_ade_e,5.119435,0.000000e+00,Adenine exchange,ade_e <=>
1261,EX_akg_e,1.167765,-3.179590e-16,2-Oxoglutarate exchange,akg_e <=>
1263,EX_ala_D_e,-1.000000,-5.133582e-16,D-Alanine exchange,ala_D_e <=>
1277,EX_arg_L_e,-1.000000,-1.316672e-14,L-Arginine exchange,arg_L_e <=>
1279,EX_asn_L_e,-1.000000,-2.122567e-15,exchange reaction for L-asparagine,asn_L_e <=>
1281,EX_asp_L_e,-1.000000,-1.316198e-15,L-Aspartate exchange,asp_L_e <=>
1289,EX_biocyt_e,-0.893613,0.000000e+00,Biocytin exchange,biocyt_e <=>
1290,EX_btn_e,0.893613,-1.886925e-19,Biotin exchange,btn_e <=>
1300,EX_chol_e,-0.547688,6.743931e-17,exchange reaction for Choline,chol_e <--
1302,EX_chsterol_e,-0.065244,0.000000e+00,exchange reaction for cholesterol,chsterol_e <=>
1304,EX_cit_e,2.429304,0.000000e+00,Citrate exchange,cit_e <=>
1309,EX_co2_e,8.129563,0.000000e+00,CO2 exchange,co2_e <=>
1311,EX_creat_e,-0.148933,0.000000e+00,Creatine exchange,creat_e <=>
1313,EX_crn_e,-0.805154,0.000000e+00,exchange reaction for L-Carnitine,crn_e <--
1329,EX_dcyt_e,-0.886823,0.000000e+00,exchange reaction for Deoxycytidine,dcyt_e <--
1337,EX_din_e,-11.836883,0.000000e+00,exchange reaction for Deoxyinosine,din_e <--
1358,EX_fol_e,-2.095668,0.000000e+00,exchange reaction for Folate,fol_e <--
1375,EX_gal_e,-0.055921,0.000000e+00,exchange reaction for D-Galactose,gal_e <--
1388,EX_gln_L_e,-1.000000,-1.655531e-15,exchange reaction for L-glutamine,gln_L_e <=>
1414,EX_hco3_e,-2.177340,0.000000e+00,Bicarbonate exchange,hco3_e <=>
1416,EX_hdca_e,-0.055921,0.000000e+00,Hexadecanoate (n-C16:0) exchange,hdca_e <=>
1420,EX_his_L_e,-4.316692,0.000000e+00,exchange reaction for L-histidine,his_L_e <--
1426,EX_hxan_e,11.836883,0.000000e+00,Hypoxanthine exchange,hxan_e <=>
1431,EX_inost_e,-0.074563,0.000000e+00,myo-Inositol exchange,inost_e <=>
1452,EX_lneldc_e,3.436749,0.000000e+00,linoelaidic acid exchange,lneldc_e <=>
1457,EX_lys_L_e,-1.000000,-1.780832e-15,L-Lysine exchange,lys_L_e <=>
1464,EX_mercplaccys_e,0.425532,0.000000e+00,3-mercaptolactate-cysteine disulfide exchange,mercplaccys_e <=>
1465,EX_met_L_e,4.990899,0.000000e+00,L-Methionine exchange,met_L_e <=>
1466,EX_mthgxl_e,15.776851,0.000000e+00,Methylglyoxal exchange,mthgxl_e <=>
1473,EX_nh4_e,6.866722,0.000000e+00,Ammonia exchange,nh4_e <=>
1475,EX_no_e,-1.000000,3.844747e-15,exchange reaction for NO,no_e <=>
1480,EX_o2_e,-6.933845,0.000000e+00,exchange reaction for oxugen,o2_e <--
1484,EX_ocdca_e,-2.728977,0.000000e+00,echange reaction for octadecanoate (n-C18:0),ocdca_e <--
1485,EX_ocdcea_e,-0.093444,0.000000e+00,octadecenoate (n-C18:1) exchange,ocdcea_e <=>
1489,EX_orn_e,-1.000000,-4.691196e-15,Ornithine exchange,orn_e <=>
1498,EX_phe_L_e,-0.829787,0.000000e+00,exchange reaction for L-phenylalanine,phe_L_e <--
1502,EX_pi_e,-3.970111,0.000000e+00,Phosphate exchange,pi_e <=>
1507,EX_pro_L_e,1.000000,0.000000e+00,L-Proline exchange,pro_L_e <=>
1528,EX_Rtotal2_e,0.055921,0.000000e+00,R total 2 position exchange,Rtotal2_e <=>
1529,EX_Rtotal3_e,0.904081,0.000000e+00,R total 3 position exchange,Rtotal3_e <=>
1535,EX_ser_L_e,-1.000000,-9.750419e-16,exchange reaction for L-serine,ser_L_e <=>
1544,EX_strdnc_e,-0.707771,0.000000e+00,stearidonic acid exchange,strdnc_e <=>
1545,EX_succ_e,0.531917,0.000000e+00,Succinate exchange,succ_e <=>
1547,EX_tag_hs_e,-0.904081,0.000000e+00,triacylglycerol (homo sapiens) exchange,tag_hs_e <=>
1558,EX_thf_e,2.095668,0.000000e+00,"5,6,7,8-Tetrahydrofolate exchange",thf_e <=>
1562,EX_thr_L_e,-1.000000,-6.396111e+00,L-Threonine exchange,thr_L_e <=>
1564,EX_thymd_e,-0.041866,0.000000e+00,Thymidine exchange,thymd_e <=>
1571,EX_trp_L_e,-0.042553,0.000000e+00,L-Tryptophan exchange,trp_L_e <=>
1580,EX_tyr_L_e,-0.510637,0.000000e+00,L-Tyrosine exchange,tyr_L_e <=>
1583,EX_ura_e,4.215335,0.000000e+00,Uracil exchange,ura_e <=>
1584,EX_urate_e,1.000000,0.000000e+00,Urate exchange,urate_e <=>
1586,EX_uri_e,-1.000000,2.314829e-16,exchange reaction for Uridine,uri_e <=>
1589,EX_val_L_e,-1.000000,-3.468507e-15,L-Valine exchange,val_L_e <=>
3751,EX_HC00250_e,-1.000000,5.154082e-17,Exchange of hydrosulfide,HC00250_e <=>
3756,EX_HC01444_e,0.055921,0.000000e+00,Exchange of Galactosylglycerol,HC01444_e <=>
3767,EX_ptrc_e,1.000000,0.000000e+00,"Exchange of 1,4-butanediammonium",ptrc_e <=>
6697,EX_citr_L_e,-1.000000,-1.219790e-14,L-citrulline exchange,citr_L_e <=>
6782,EX_CE0074_e,-1.000000,1.234695e-14,alloxan exchange,CE0074_e <=>
6897,EX_3ivcrn,0.805154,0.000000e+00,exchange reaction for 3-hydroxy-isovaleryl car...,3ivcrn_e <=>
7318,EX_leuleu_e,-0.389562,0.000000e+00,exchange reaction for leucylleucine,leuleu_e <--
7425,EX_3mob_e,-0.127657,0.000000e+00,Exchange of 3-methyl-2-oxobutanoate,3mob_e <=>
7426,EX_3mop_e,-0.914893,0.000000e+00,Exchange of 3-methyl-2-oxopentanoate,3mop_e <=>
7427,EX_4mop_e,-0.965557,0.000000e+00,Exchange of 4-methyl-2-oxopentanoate,4mop_e <=>
7430,EX_ahcys_e,-5.480259,0.000000e+00,Exchange of S-adenosyl-L-homocysteine,ahcys_e <=>
7433,EX_cbasp_e,-2.654470,0.000000e+00,Exchange of N-carbamoyl-L-aspartate,cbasp_e <=>

,rxn_ids,fluxes,reduced_costs,rxn_names,rxn_reaction
330,AHEXASE2ly,1.536584e-17,-9.860761e-32,"beta-N-acetylhexosaminidase, lysosomal",3.0 h2o_l + n2m2nmn_l --> 3.0 acgam_l + m2mn_l
331,AHEXASEly,2.393918e-16,0.000000e+00,"beta-N-acetylhexosaminidase, lysosomal",2.0 h2o_l + n2m2mn_l --> 2.0 acgam_l + m2mn_l
1193,EX_10fthf_e,0.000000e+00,0.000000e+00,10-Formyltetrahydrofolate exchange,10fthf_e <=>
1194,EX_10fthf5glu_e,0.000000e+00,0.000000e+00,10-formyltetrahydrofolate-[Glu](5) exchange,10fthf5glu_e <=>
1195,EX_10fthf6glu_e,0.000000e+00,0.000000e+00,10-formyltetrahydrofolate-[Glu](6) exchange,10fthf6glu_e <=>
...,...,...,...,...,...
7431,EX_aicar_e,0.000000e+00,0.000000e+00,Exchange of 5-amino-1-(5-phospho-D-ribosyl)imi...,aicar_e -->
7432,EX_anth_e,0.000000e+00,0.000000e+00,Exchange of anthranilate,anth_e <=>
7433,EX_cbasp_e,-2.654470e+00,0.000000e+00,Exchange of N-carbamoyl-L-aspartate,cbasp_e <=>
7434,EX_mal_L_e,0.000000e+00,1.166960e-15,Exchange of L-malate,mal_L_e <=>
7439,EX_idour_e,0.000000e+00,0.000000e+00,Exchange of L-iduronate,idour_e <=>

## Parsimonious FBA

pfba_solution = cobra.flux_analysis.pfba(normal)
sol_normal = pfba_solution

phe_L_fluxes   = sol_normal.fluxes[phe_L_ids].to_frame() #.query('abs(fluxes) > 1e-7', inplace=True)
phe_L_fluxes.query('abs(fluxes) > 1e-7', inplace=True)
phe_L_fluxes = phe_L_fluxes.rename_axis('phe_L_e_ids').reset_index()
pd.merge(phe_L_fluxes, phe_L)

tyr_L_fluxes   = sol_normal.fluxes[tyr_L_ids].to_frame()  #.query('abs(fluxes) > 1e-7', inplace=True)
tyr_L_fluxes.query('abs(fluxes) > 1e-7', inplace=True)
tyr_L_fluxes = tyr_L_fluxes.rename_axis('tyr_L_e_ids').reset_index()
pd.merge(tyr_L_fluxes, tyr_L)

## geometric FBA

geometric_fba_sol = cobra.flux_analysis.geometric_fba(normal, epsilon=1e-01, max_tries=50)
sol_normal = geometric_fba_sol
phe_L_fluxes   = sol_normal.fluxes[phe_L_e_ids].to_frame() #.query('abs(fluxes) > 1e-7', inplace=True)
phe_L_fluxes.query('abs(fluxes) > 1e-7', inplace=True)
phe_L_fluxes = phe_L_fluxes.rename_axis('phe_L_e_ids').reset_index()
pd.merge(phe_L_fluxes, phe_L)